<a href="https://colab.research.google.com/github/NATO-dotcom/ML-AI_Python/blob/main/filtering_np_arrays_using_boolean_index_lists.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
np1=np.array([1,2,3,4,5,6,7,8,9])
filtered=[]
for thing in np1:
  if thing % 2==0:
    filtered.append(True)
  else:
      filtered.append(False)
print(np1)
print(filtered)
print(np1[filtered])


[1 2 3 4 5 6 7 8 9]
[False, True, False, True, False, True, False, True, False]
[2 4 6 8]


In [ ]:
np2=np.array([1,2,3,4,5,6,7,8,9])
filtered=[]
for thing in np2:
  if thing > 5:
    filtered.append(True)
  else:
      filtered.append(False)
print(np2)
print(filtered)
print(np2[filtered])

[1 2 3 4 5 6 7 8 9]
[False, False, False, False, False, True, True, True, True]
[6 7 8 9]


In [ ]:
#shortcut
filtered=np1%2==0
print(np1)
print(filtered)
print(np1[filtered])

[1 2 3 4 5 6 7 8 9]
[False  True False  True False  True False  True False]
[2 4 6 8]


In [ ]:
filtered=np2>5
print(np2)
print(filtered)
print(np2[filtered])

[1 2 3 4 5 6 7 8 9]
[False False False False False  True  True  True  True]
[6 7 8 9]
