<a href="https://colab.research.google.com/github/NATO-dotcom/ML-AI_Python/blob/main/introduction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
#numpy means numeric python
#data ytpe=ndarray i.e. n-dimensional array
#it's a special array
np1=np.array([0,1,2,3,4,5,6,7,8,9])
np1#or print(np1)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
np1.shape#the number of elementa in an array

(10,)

In [5]:
np2=np.arange(10)#default step size is 1 for elememts between 0 to 10(excluded)
np2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
np3=np.arange(0,10,2)#array elements starting from 0 up to 10(excluded),with a step size of 2
np3

array([0, 2, 4, 6, 8])

In [8]:
np4=np.arange(2,50,5)
np4

array([ 2,  7, 12, 17, 22, 27, 32, 37, 42, 47])

In [9]:
np5=np.zeros(10)#array of 10 elements as zeros
np5

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [12]:
#1D array of size 5 with 7 as the elements
np7=np.full(5,7)
np7

array([7, 7, 7, 7, 7])

In [11]:
np6=np.ones(5)
np6

array([1., 1., 1., 1., 1.])

In [17]:
np6a=np.ones((2,3))#2D array of elemets filled with ones
np6a

array([[1., 1., 1.],
       [1., 1., 1.]])

In [13]:
np8=np.full((5,8),5)#a 2D array with 5 as the elements
np8

array([[5, 5, 5, 5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5, 5, 5, 5]])

In [15]:
np9=np.full((10),6)#a 1D array filled with 6
np9

array([6, 6, 6, 6, 6, 6, 6, 6, 6, 6])

In [23]:
#coverting a python list to numpy
py_list=[1,2,3,4,5,6,7,8,9]
np10=np.array(py_list)
print(np10)
print(type(np10))#data type
print(type(py_list))
print(np10[0])#accessing elements in an array e.g array in index 0

[1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>
<class 'list'>
1
