<a href="https://colab.research.google.com/github/NATO-dotcom/ML-AI_Python/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [3]:
np1=np.array([1,2,3,4,5,6,7,8,9])#1D
print(np1)

[1 2 3 4 5 6 7 8 9]


In [4]:
np2=np.array([[1,2,3],[4,5,6],[7,8,9]])#2D
print(np2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [7]:
np3=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])#3D
print(np3)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [8]:
np2.shape

(3, 3)

In [10]:
np2.size#number elements

9

In [14]:
np4=np1.reshape(3,3)#reshaping an array
print(np4)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [15]:
np5=np.ones(10)#array of ones
print(np5)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [16]:
np6=np.zeros(5)#array of zeros
print(np6)

[0. 0. 0. 0. 0.]


In [19]:
np7=np.full(4,3)
print(np7)

[3 3 3 3]


In [20]:
a=np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
b=np.arange(1,10,2)
b

array([1, 3, 5, 7, 9])

In [24]:
c=np.zeros((2,3))
c

array([[0., 0., 0.],
       [0., 0., 0.]])

In [25]:
d=np.full((2,3),4)
d

array([[4, 4, 4],
       [4, 4, 4]])

In [31]:
np8=np.array([1,2,3,4,5,6,7,8,9,10])
print(np.sqrt(np8))
print(np.min(np8))
print(np.exp(np8))
print(np.cos(np8))

[1.         1.41421356 1.73205081 2.         2.23606798 2.44948974
 2.64575131 2.82842712 3.         3.16227766]
1
[2.71828183e+00 7.38905610e+00 2.00855369e+01 5.45981500e+01
 1.48413159e+02 4.03428793e+02 1.09663316e+03 2.98095799e+03
 8.10308393e+03 2.20264658e+04]
[ 0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219  0.96017029
  0.75390225 -0.14550003 -0.91113026 -0.83907153]


In [36]:
np9=np.array([1,2,3,4,5,6,7,8,9,10])
print(np9[2::2])

[3 5 7 9]


In [49]:
np10=np.random.randint(10,20,size=(5,5))
print(np10)

[[15 10 12 13 14]
 [18 12 18 12 18]
 [16 13 10 16 11]
 [13 10 13 15 11]
 [16 17 16 11 12]]


In [52]:
np11=np.random.rand(2,3,5)
np11

array([[[0.72709936, 0.67100517, 0.77252034, 0.24457391, 0.6879674 ],
        [0.39123398, 0.65411611, 0.33138821, 0.6093031 , 0.5467424 ],
        [0.33242503, 0.17390094, 0.98159891, 0.52544505, 0.5376485 ]],

       [[0.83330777, 0.16879164, 0.74672774, 0.47190567, 0.20766205],
        [0.05934743, 0.1492658 , 0.78390584, 0.07866002, 0.25726869],
        [0.89378324, 0.44206111, 0.24524005, 0.60041424, 0.18390226]]])