In [37]:
import numpy as np

In [2]:
np=[1,2,3,4,5,6,7,8,9,10]
np

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [9]:
np.full((3,3),1)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [10]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [12]:
np.arange(10,50,5)

array([10, 15, 20, 25, 30, 35, 40, 45])

In [24]:

arr1=np.array([1,2,3,4,5,])
arr2=np.array([6,7,8,9,10])
addition=arr1+arr2
multiplication=arr1*arr2
dot_product=np.dot(arr1,arr2)
max1=np.max(arr1)
max2=np.max(arr2)
min1=np.min(arr1)
min2=np.min(arr2)
mean1=np.mean(arr1) 
mean2=np.mean(arr2)
print("max1:",max1)
print("max2:",max2)
print("min1:",min1)
print("min2:",min2)
print("mean1:",mean1)
print("mean2:",mean2)
print("addition:",addition) 
print("multiplication:",multiplication)
print("dot_product:",dot_product)


max1: 5
max2: 10
min1: 1
min2: 6
mean1: 3.0
mean2: 8.0
addition: [ 7  9 11 13 15]
multiplication: [ 6 14 24 36 50]
dot_product: 130


In [ ]:
arr=np.random.randint(1,100,(5,5))
print(arr)

[[89 60 41 29 15]
 [45 65 89 71  9]
 [88  1  8 88 63]
 [11 81  8 35 35]
 [33  5 41 28  7]]


In [46]:
first_row=arr[0]
last_row=arr[-1]
first_column=arr[:,0]
last_column=arr[:,-1]
print("first_row:",first_row)
print("last_row:",last_row)
print("first_column:",first_column)
print("last_column:",last_column)

first_row: [89 60 41 29 15]
last_row: [33  5 41 28  7]
first_column: [89 45 88 11 33]
last_column: [15  9 63 35  7]


In [48]:
middle_subarray=arr[1:3,1:3]
print("middle_subarray:",middle_subarray)


middle_subarray: [[65 89]
 [ 1  8]]


In [49]:
arr[arr>50]=0
print(arr)

[[ 0  0 41 29 15]
 [45  0  0  0  9]
 [ 0  1  8  0  0]
 [11  0  8 35 35]
 [33  5 41 28  7]]
