<a href="https://colab.research.google.com/github/NATO-dotcom/ML-AI_Python/blob/main/recap.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
a=np.array([1,2,3,4,5,6])
print(a)

[1 2 3 4 5 6]


In [3]:
b=np.array([[2.0,3.0,5.0,7.0],[5.0,9.0,6.0,4.0]])
print(b)

[[2. 3. 5. 7.]
 [5. 9. 6. 4.]]


In [5]:
#get dimensions
#a.ndim
b.ndim

2

In [7]:
#get shape
a.shape
b.shape

(2, 4)

In [8]:
#get data type
b.dtype

dtype('float64')

In [10]:
#get size
b.size
b.itemsize

8

In [13]:
#get total size
b.nbytes
b.size*b.itemsize

64