<a href="https://colab.research.google.com/github/NATO-dotcom/ML-AI_Python/blob/main/recap2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [22]:
import  numpy as np

In [23]:
a=np.array([[1,2,3,4,5,6],[7,8,9,10,11,12]])
print(a)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [24]:
#get a specific element [r,c]
print(a[1,5])

12


In [25]:
#get a specific row
print(a[0,:])

[1 2 3 4 5 6]


In [26]:
#get a specific column
print(a[:,2])

[3 9]


In [27]:
print(a[0,1:5:2])#accessing elements in step size

[2 4]


In [31]:
a[1:4]=14#note this
print(a)

[[ 1  2  3  4  5  6]
 [14 14 14 14 14 14]]


In [32]:
a[:,:]=15#set all elements to 15
print(a)

[[15 15 15 15 15 15]
 [15 15 15 15 15 15]]


In [33]:
a[0,1]=6#do this if its a single index
print(a)

[[15  6 15 15 15 15]
 [15 15 15 15 15 15]]
