<a href="https://colab.research.google.com/github/NATO-dotcom/ML-AI_Python/blob/main/search.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
np1=np.array([1,2,3,4,5,6,7,8,9])#we use the fn where
x=np.where(np1==5)#prints the index of what you are searching
print(np1)
print(x)#prints a tuple

[1 2 3 4 5 6 7 8 9]
(array([4]),)


In [3]:
np2=np.array([1,2,3,4,5,6,7,8,9])#prints even numbers
x=np.where(np2%2==0)#prints the index of what you are searching
print(np2)
print(x[0])#do away with the tuple

[1 2 3 4 5 6 7 8 9]
[1 3 5 7]


In [5]:
np3=np.array([1,2,3,4,5,6,7,8,9,3])
y=np.where(np3==3)
print(np3)
print(y[0])

[1 2 3 4 5 6 7 8 9 3]
[2 9]


In [7]:
np3=np.array([1,2,3,4,5,6,7,8,9,3])
y=np.where(np3==3)
print(np3)
print(y[0])
print(np3[y[0]])#when you want the real thing you searching

[1 2 3 4 5 6 7 8 9 3]
[2 9]
[3 3]
