<a href="https://colab.research.google.com/github/NATO-dotcom/ML-AI_Python/blob/main/shape_and_reshape_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
np1=np.array([1,2,3,4,5,6,7,8,9])#1D array
print(np.shape(np1))

(9,)


In [4]:
np2=np.array([[1,2,3,4,5],[6,7,8,9,10]])#1D array
print(np.shape(np2))#returns rows and columns

(2, 5)


In [8]:
np3=np1.reshape(3,3)#creating a 2D array BY RESHAPING
print(np3)
print(np.shape(np3))#to confirm our shape

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)


In [10]:
np4=np1.reshape(3,3,1)#creating a 3D array BY RESHAPING
print(np4)#3 blocks of 3 by 1
print(np.shape(np4))#to confirm our shape

[[[1]
  [2]
  [3]]

 [[4]
  [5]
  [6]]

 [[7]
  [8]
  [9]]]
(3, 3, 1)


In [13]:
np5=np4.reshape(-1)#reshaping our array back to 1D
print(np5)
print(np.shape(np5))

[1 2 3 4 5 6 7 8 9]
(9,)
