<a href="https://colab.research.google.com/github/NATO-dotcom/ML-AI_Python/blob/main/Slicing_np_arrays.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [19]:
#slicing a 1D array
np1=np.array([1,2,3,4,5,6,7,8,9])#in slicing np the last index is always excluded
#return 2,3,4,5
print(np1[1:5])
#return 3,4,5,6,7:like elements in index 2 to 7
print (np1[2:7])
#return from sth to the end of the array
print(np1[2:])
#return negative slices:like counting from backwards
print(np1[-3:-1])
#steps
print(np1[1:5:2])#return 2-5 in steps of 2
print(np1[::2])#return the entire array in steps of 2
print(np1[::3])#return the entire array in steps of 3
print(np1[1::2])#return from array index 1 in steps of 2
print(np1[::-1])#return reversed array

[2 3 4 5]
[3 4 5 6 7]
[3 4 5 6 7 8 9]
[7 8]
[2 4]
[1 3 5 7 9]
[1 4 7]
[2 4 6 8]
[9 8 7 6 5 4 3 2 1]


In [18]:
#slicing a 2D array
np2=np.array([[1,2,3,4,5],[6,7,8,9,10]])
#pull out a single item
print(np2[1,2])#from the 1st index (row 2),the second index element
#slicing
print(np2[1,1:4])#slice in array 2 only(index 1)
print(np2[0,2:5])#we want to slice array 1(index 0)
print(np2[0:1,1:3])#we want to slice in array 1 only
print(np2[0:2,2])#we want elements index two in both arrays
print(np2[0:2,1:4])#in both arrays we want elements within from index 1 to 4(excluded)


8
[7 8 9]
[3 4 5]
[[2 3]]
[3 8]
[[2 3 4]
 [7 8 9]]


In [26]:
#slicing 3D array(depth*rows*columns)
#a stack of 2D matrices
np3=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(np3[0,1,2])


6
